[tool.poetry]
name = "gce-ipx800-prometheus"
version = "0.1.0"
description = "wend endpoint exposing prometheus metrics for a GCE IPX800 device."
authors = ["Marc-Aurèle Brothier <m@brothier.org>"]
license = "Apache-2.0"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
fastapi = "^0.104.0"
urllib3 = "^2.0.7"
uvicorn = "^0.23.2"
gce-ipx800 = "^0.5.2"


[tool.poetry.group.dev.dependencies]
ruff = "^0.1.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
