[tool.poetry]
name = "gce-ipx800-prometheus"
version = "0.0.0"
description = "wend endpoint exposing prometheus metrics for a GCE IPX800 device."
authors = ["Marc-Aurèle Brothier <m@brothier.org>"]
license = "Apache-2.0"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
fastapi = "^0.109.1"
urllib3 = "^2.2.0"
uvicorn = "^0.27.0"
gce-ipx800 = "^0.5.2"


[tool.poetry.group.dev.dependencies]
ruff = "^0.3.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
