---
name: Build Container Image

on:
  pull_request:
    branches:
      - main

jobs:
  build-container:
    name: Build amd64 and arm64 container images
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4.2.2

      - name: Extract metadata (tags, labels) for image
        id: meta
        uses: docker/metadata-action@v5.7.0
        with:
          images: |
            marcaurele/gce-ipx800-prometheus
            ghcr.io/${{ github.repository }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3.6.0
        with:
          platforms: amd64,arm64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.11.1

      - name: Build container image
        uses: docker/build-push-action@v6.18.0
        with:
          context: .
          file: Containerfile
          platforms: linux/amd64,linux/arm64
          push: false
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}